---
title: "Homework-3"
author: "Alex Steiner"
date: "2024-01-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


These are my answers to HW #3 in Bio381, solving regex puzzles. 

Reference questions can be found at this [link](https://gotellilab.github.io/Bio381/Homeworks/Homework_03.html).


### Question 1
 Find:```\s{2, }```

 Replace:,

 Explanation: I searched for 2 or more white spaces in a row, and replaced with a comma.


### Question 2
Find: ```(\w+), (\w+), (.+)```

Replace: ```\2 \1 \(\3\)```

Explanation: I selected the first character string followed by a comma and designated it together as 1. selected second word and grouped it as 2, and Selected everything after the second comma and grouped it as 3.
I replaced it with the second group first, followed by the first group, and finally the last group, in between parantheses (which I needed to designate as not an expression with forward slashes).


### Question 3
Find: ```(?<=mp3)\s```

Replace: ```\n```

Explanation: I select the space that is preceeded by "mp3" and replace it with a new line. 


### Question 4
Find:```(\d{2, }) (.+(?=.mp3))```

Replace:```\2\_\1```

Explanation: Selected strings with more than one number and assigned as group 1 (to exclude the 3 in mp3). Skipped space. Selected anything before .mp3 and assigned as group 2. I replaced it with group 2 followed by an underscore and then group 1. 


### Question 5
Find:```(\w)\w+,(\w+)(.+)((?<=,)\d+$)```

Replace: ```\1_\2\,\4```

Explanation:
Selected the first letter of the genus name as group one, selected the rest of the genus name. Selected the whole specific epithet as group 2.Selected the number(s) at the end which was following a comma, and grouped it as 4. 
Replaced with grouping one followed by an underscore, grouping two followed by a comma and then grouping 4. Ignored grouping 3. 


### Question 6
Find: ```(\w)\w+,(\w{4})(.+)((?<=,)\d+$)```

Replace: ```\1_\2\,\4```

Explanation: 
Similar to the above question, I selected the first character of the genus name and grouped it as 1. I selected the first 4 characters of the specific epithet and grouped as 2. Selected the number(s) at the end which was following a comma, and grouped it as 4. 
Replaced with grouping one followed by an underscore, grouping two followed by a comma and then grouping 4. Ignored grouping 3. 

### Question 7
Find: ```(\w{3})\w+,(\w{3})\w+,(\d*\.?\d*),(\d*) ```

Replace```\1\2, \4, \3```

Explanation: 
First 3 letters of the genus name and grouped as 1. Selected the rest of the letters followed by a comma. Selected the first three letters of the specific epithet and grouped as 2. Selected the rest of the letters in the specific epithet followed by the comma. Selected the number(s) potentially with a period between them grouped them as 3. Selected the numbers following the comma after the last selection. 
Replaced them with group 1 and group two with no spaces, a comma and space followed by group 4 another comma and space followed by group 3.

